services:
  db:
    image: postgres:16
    container_name: pg
    environment:
      POSTGRES_USER: sasun
      POSTGRES_PASSWORD: appointme
      POSTGRES_DB: appoint_me
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sasun -d appoint_me"]
      interval: 5s
      timeout: 3s
      retries: 20

  # # Optional but very useful for bot state/OTP/rate-limit
  # redis:
  #   image: redis:7
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redisdata:/data
  #   command: ["redis-server", "--appendonly", "yes"]
volumes:
  pgdata:
  redisdata:
